'use client';

import React from 'react';
import PageBackLink from '@/components/PageBackLink';

const sections: { title: string; content: string | string[] }[] = [
  {
    title: 'General Terms',
    content: [
      'By accessing and placing an order with BISA, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and BISA.',
      'Under no circumstances shall BISA team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site.',
      'BISA will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.',
    ],
  },
  {
    title: 'Licence',
    content: [
      'BISA grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website/app strictly in accordance with the terms of this Agreement.',
      'These Terms & Conditions are a contract between you and BISA, the provider of the BISA website and the services accessible from the BISA website.',
      'You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the BISA Service.',
    ],
  },
  {
    title: 'Definitions and Key Terms',
    content: [
      'Cookie: small amount of data generated by a website and saved by your web browser.',
      'Company: when this terms mention "Company," "we," "us," or "our," it refers to BISA (Biochar Indonesia Sirkular Agriculture), based in Lombok Tengah, Nusa Tenggara Barat, Indonesia.',
      'Country: where BISA or the owners/founders of BISA are based, in this case is Indonesia.',
      'Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit BISA and use the services.',
      'Service: refers to the service provided by BISA as described in the relative terms and on this platform.',
      'You: a person or entity that is registered with BISA to use the Services.',
    ],
  },
  {
    title: 'Restrictions',
    content: [
      'You agree not to license, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website/app or make the platform available to any third party.',
      'You agree not to modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website/app.',
      'You agree not to remove, alter or obscure any proprietary notice of BISA or its affiliates, partners, suppliers or the licensors of the website/app.',
    ],
  },
  {
    title: 'Return and Refund Policy',
    content: 'Thanks for shopping at BISA. As with any shopping experience, there are terms and conditions that apply to transactions at BISA. If, for any reason, You are not completely satisfied with any good or service that we provide, don\'t hesitate to contact us and we will discuss any of the issues you are going through with our product.',
  },
  {
    title: 'Your Suggestions',
    content: 'Any feedback, comments, ideas, improvements or suggestions provided by you to BISA with respect to the website/app shall remain the sole and exclusive property of BISA.',
  },
  {
    title: 'Your Consent',
    content: 'By using our website/app, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.',
  },
  {
    title: 'Links to Other Websites',
    content: 'This Terms & Conditions applies only to the Services. The Services may contain links to other websites not operated or controlled by BISA. We are not responsible for the content, accuracy or opinions expressed in such websites.',
  },
  {
    title: 'Cookies',
    content: 'BISA uses "Cookies" to identify the areas of our website/app that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website/app.',
  },
  {
    title: 'Term and Termination',
    content: 'This Agreement shall remain in effect until terminated by you or BISA. BISA may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.',
  },
  {
    title: 'No Warranties',
    content: 'The website/app is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, BISA expressly disclaims all warranties, whether express, implied, statutory or otherwise.',
  },
  {
    title: 'Limitation of Liability',
    content: 'Notwithstanding any damages that you might incur, the entire liability of BISA and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the website/app.',
  },
  {
    title: 'Contact Us',
    content: 'Don\'t hesitate to contact us if you have any questions. Contact us at hello@bisa.id.',
  },
];

export default function TermsAndConditionsPage() {
  return (
    <div className="bg-white min-h-screen pt-header pb-24">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
        <PageBackLink />

        <div className="space-y-3">
          <p className="text-xs font-semibold text-elevarm-grey">Current as of 20 March 2024</p>
          <h1 className="text-3xl sm:text-4xl font-bold text-elevarm-black font-display tracking-tight">
            Terms and Conditions
          </h1>
          <p className="text-elevarm-grey text-sm leading-relaxed">
            By accessing our website, you are agreeing to be bound by these terms of service, and agree that you are responsible for compliance with any applicable local laws
          </p>
        </div>

        <div className="text-sm text-elevarm-grey leading-relaxed space-y-8">
          {sections.map((section) => (
            <div key={section.title} className="space-y-3">
              <h3 className="text-sm font-bold text-elevarm-black">{section.title}</h3>
              {Array.isArray(section.content) ? (
                <div className="space-y-2">
                  {section.content.map((p) => (
                    <p key={p.slice(0, 40)}>{p}</p>
                  ))}
                </div>
              ) : (
                <p>{section.content}</p>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
